### ISSUE TITLE
FoV in Blender does not match FoV ingame

### ISSUE THREAD

**Issue by HollyMagala** [AsgardXIV/XAT#3]
Adjusting focal length in Blender also adjusts FoV ingame, but the two don't match.
![image](https://user-images.githubusercontent.com/66383913/206242988-cf459fee-c72b-4b58-af67-ed4867eb6aa0.png)
The difference between the focal length and what it has to be is kinda like this: (rough measurements)
![image](https://user-images.githubusercontent.com/66383913/206243423-3e244034-59d5-45e1-80e1-bf725ae0ef0b.png)
I don't know if this is intentional or not, but it makes mimicking shots from the game in blender very difficult.

I didn't touch the in-game fov slider, since that seemed to interact weirdly with the camera.

**Comment by asgardkat** [comment]
It looks like it's slightly off. I am not 100% sure why.

Can you try adjusting the angle in GPose to 120 (from the 100 default)? That seems to be about right.
That would mean it's about 5-6 degrees off, just want to confirm if that's what you see as well.

I think I might know why, but I am gonna look some more.

**Comment by asgardkat** [comment]
I've pushed out a new version of the blender plugin that should be more accurate, might not be perfect still though: https://github.com/AsgardXIV/XAT/releases/tag/v2022.12.7.2047

**Comment by HollyMagala** [comment]
I'm still having issues in the new version, (at least, I _think_ I installed it correctly? tried a few times,) and adjusting angle ingame required around 145 to make it fit, for a shot from 3.5m away, 70mm focal length. Might try a few more distances and see whether adjustment changes.

**Comment by asgardkat** [comment]
Hah, I think I might know why. The math the game uses for this is... odd. 
I think it will actually require a plugin update, let me get back to you.

**Comment by HollyMagala** [comment]
No worries! Good luck

**Comment by asgardkat** [comment]
With the new version I just posted (grab the blender addon and install), can you try and set the Sensor Fit in Blender to "Vertical"?

![image](https://user-images.githubusercontent.com/95163444/206368368-930c2e9f-b99a-4e5f-bd80-5bdfa8e3238e.png)

**Comment by HollyMagala** [comment]
That works! I think it might still be _ever so slightly_ off, but I'm genuinely unsure. I think this is accurate enough. 👍

**Comment by asgardkat** [comment]
Yeh, I am not sure if it will ever be 100% accurate unless we can figure out exactly how the FFXIV camera is configured in terms of the lens angle. 

This seems to be very close though, especially in the mid ranges, and extremely low or high FoVs in FFXIV look bad anyway.

So I think for most cases this will be so close it won't make a significant difference (that can't be overcome with the scaling and offset options already available in XAT. For example you could move the zoom out if the FoV is slightly too low).
